//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int TypeID { get; set; }
        public int UniqueID { get; set; }
        public string CommentText { get; set; }
        public int MemberID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ParentCommentID { get; set; }
        public string ClientIP { get; set; }
        public Nullable<int> AdminID { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
