//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public Entry()
        {
            this.EntryTag = new HashSet<EntryTag>();
            this.FeedBack = new HashSet<FeedBack>();
        }
    
        public int EntryID { get; set; }
        public int StoryID { get; set; }
        public int MemberID { get; set; }
        public string EntryText { get; set; }
        public bool IsAnonymous { get; set; }
        public Nullable<bool> IsChosen { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusID { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> AdminDate { get; set; }
        public Nullable<int> PageNo { get; set; }
        public bool IsParagraphStart { get; set; }
        public int TotalVotes { get; set; }
        public int VotesAvg { get; set; }
        public bool IsTagged { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Story Story { get; set; }
        public virtual ICollection<EntryTag> EntryTag { get; set; }
        public virtual ICollection<FeedBack> FeedBack { get; set; }
    }
}
