//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryTag
    {
        public int EntryTagID { get; set; }
        public int EntryID { get; set; }
        public int TagID { get; set; }
        public int TagTypeID { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
