//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeedBackID { get; set; }
        public int MemberID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string TextInfo { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
