//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Comment = new HashSet<Comment>();
            this.FeedBack = new HashSet<FeedBack>();
            this.Entry = new HashSet<Entry>();
            this.Follow = new HashSet<Follow>();
            this.StoryMember = new HashSet<StoryMember>();
            this.Story = new HashSet<Story>();
        }
    
        public int MemberID { get; set; }
        public string FaceID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberName { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> FirstVisitDate { get; set; }
        public string FirstVisitIP { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public string LastVisitIP { get; set; }
        public string AvatarCode { get; set; }
        public int VoteMultiplier { get; set; }
        public Nullable<int> AdminRoleID { get; set; }
        public string TwitterTokens { get; set; }
        public string LinkedinJob { get; set; }
        public int FollowerCount { get; set; }
        public string TwitterID { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<FeedBack> FeedBack { get; set; }
        public virtual ICollection<Entry> Entry { get; set; }
        public virtual ICollection<Follow> Follow { get; set; }
        public virtual ICollection<StoryMember> StoryMember { get; set; }
        public virtual ICollection<Story> Story { get; set; }
    }
}
