//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryState
    {
        public StoryState()
        {
            this.Story = new HashSet<Story>();
        }
    
        public int StoryStateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Story> Story { get; set; }
    }
}
