//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryMember
    {
        public int StoryMemberID { get; set; }
        public int StoryID { get; set; }
        public int MemberID { get; set; }
        public int TypeID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Story Story { get; set; }
        public virtual Member Member { get; set; }
    }
}
