//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public Story()
        {
            this.Entry = new HashSet<Entry>();
            this.StoryMember = new HashSet<StoryMember>();
        }
    
        public int StoryID { get; set; }
        public int AdminID { get; set; }
        public string StoryName { get; set; }
        public string StoryText { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int PageCount { get; set; }
        public System.DateTime LastEntryChosenDate { get; set; }
        public int StatusID { get; set; }
        public int FirstCounter { get; set; }
        public int SecondCounter { get; set; }
        public int StateID { get; set; }
        public System.DateTime NextTickDate { get; set; }
        public bool IsPrivateView { get; set; }
        public bool IsPrivateWriting { get; set; }
        public int CharLimit { get; set; }
        public bool AllowMultipleSentences { get; set; }
    
        public virtual ICollection<Entry> Entry { get; set; }
        public virtual ICollection<StoryMember> StoryMember { get; set; }
        public virtual Member Member { get; set; }
        public virtual StoryState StoryState { get; set; }
    }
}
