//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neverending
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.EntryTag = new HashSet<EntryTag>();
        }
    
        public int TagID { get; set; }
        public string TagText { get; set; }
        public int MemberID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EntryTag> EntryTag { get; set; }
    }
}
