//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin&apos;e hoşgeldiniz.&lt;br/&gt;&lt;br/&gt;
        ///Sonsuz Metin,  kullanıcıların ortaklaşa bir şekilde, yani “cümleten” ortaya çıkardıkları bir metin. &lt;br/&gt;&lt;br/&gt;
        ///Her kullanıcı bir cümle yazıyor ve bu cümleler sağ tarafta sıralanıyor. &lt;br/&gt;&lt;br/&gt;
        ///Oylama boyunca en fazla beğeniyi alan cümle, metne ekleniyor. &lt;br/&gt;&lt;br/&gt;
        ///Eğer iki veya daha fazla cümle aynı sayıda beğeniyi aldıysa, içlerinden en az “beğenmedim”i alan cümle seçiliyor.
        ///Ve sonraki oylama başlıyor.&lt;br/&gt;&lt;br/&gt;
        ///Sonsuz Metin&apos;de herhangi bir içerik kısıtlaması k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutmessage {
            get {
                return ResourceManager.GetString("aboutmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin Hakkında.
        /// </summary>
        internal static string abouttitle {
            get {
                return ResourceManager.GetString("abouttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        internal static string allrights {
            get {
                return ResourceManager.GetString("allrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonim.
        /// </summary>
        internal static string anonym {
            get {
                return ResourceManager.GetString("anonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şu anda cümle yazamıyorsun. Ama sağ taraftan diğer cümleleri oylayabilirsin..
        /// </summary>
        internal static string cantpostnow {
            get {
                return ResourceManager.GetString("cantpostnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter.
        /// </summary>
        internal static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakterler.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketlemek istediğin kelimeyi ve ilgili etiketi seç..
        /// </summary>
        internal static string choosetagwords {
            get {
                return ResourceManager.GetString("choosetagwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin senin cümlenle devam etti,&lt;br /&gt;.
        /// </summary>
        internal static string chosenthanks {
            get {
                return ResourceManager.GetString("chosenthanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler. İlgileniyoruz..
        /// </summary>
        internal static string complaintsent {
            get {
                return ResourceManager.GetString("complaintsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebrikler!.
        /// </summary>
        internal static string congrats {
            get {
                return ResourceManager.GetString("congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonra oylamaya geçilecek!.
        /// </summary>
        internal static string countdown1 {
            get {
                return ResourceManager.GetString("countdown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonra cümle yazabilirsiniz!.
        /// </summary>
        internal static string countdown2 {
            get {
                return ResourceManager.GetString("countdown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötü.
        /// </summary>
        internal static string dislike {
            get {
                return ResourceManager.GetString("dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğenilmedi.
        /// </summary>
        internal static string disliked {
            get {
                return ResourceManager.GetString("disliked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kötü.
        /// </summary>
        internal static string dislikes {
            get {
                return ResourceManager.GetString("dislikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümleleri.
        /// </summary>
        internal static string entriesby {
            get {
                return ResourceManager.GetString("entriesby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cümle.
        /// </summary>
        internal static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümle Linki.
        /// </summary>
        internal static string entrylink {
            get {
                return ResourceManager.GetString("entrylink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takip et.
        /// </summary>
        internal static string follow {
            get {
                return ResourceManager.GetString("follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İyi.
        /// </summary>
        internal static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğenildi.
        /// </summary>
        internal static string liked {
            get {
                return ResourceManager.GetString("liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyi.
        /// </summary>
        internal static string likes {
            get {
                return ResourceManager.GetString("likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #l kere beğenildi &lt;br/&gt; #dl kere beğenilmedi.
        /// </summary>
        internal static string likesanddislikes {
            get {
                return ResourceManager.GetString("likesanddislikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yükleniyor.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncesini yükle.
        /// </summary>
        internal static string loadprev {
            get {
                return ResourceManager.GetString("loadprev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekan.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin Beta.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar Linki.
        /// </summary>
        internal static string memberlink {
            get {
                return ResourceManager.GetString("memberlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dakika.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekanlar.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonim gönderi yap.
        /// </summary>
        internal static string postanonymous {
            get {
                return ResourceManager.GetString("postanonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümleniz gönderildi.
        /// </summary>
        internal static string postedsuccesfully {
            get {
                return ResourceManager.GetString("postedsuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir sonraki cümle zamanı gelene kadar diğer cümleleri oylayabilirsin..
        /// </summary>
        internal static string readnextentries {
            get {
                return ResourceManager.GetString("readnextentries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İntihal bildir.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamdır.
        /// </summary>
        internal static string savetags {
            get {
                return ResourceManager.GetString("savetags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saniye.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu cümle seçildi!.
        /// </summary>
        internal static string sentencewaschosen {
            get {
                return ResourceManager.GetString("sentencewaschosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar sayfasını göster.
        /// </summary>
        internal static string showauthorlink {
            get {
                return ResourceManager.GetString("showauthorlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümle linkini göster.
        /// </summary>
        internal static string showentrylink {
            get {
                return ResourceManager.GetString("showentrylink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıntı olduğunu düşünüyorum&lt;br/&gt;(aşağıda nereden olduğunu belirtiniz ).
        /// </summary>
        internal static string stolen {
            get {
                return ResourceManager.GetString("stolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDER.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaman.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter ile Giriş.
        /// </summary>
        internal static string twitterconnect {
            get {
                return ResourceManager.GetString("twitterconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takibi bırak.
        /// </summary>
        internal static string unfollow {
            get {
                return ResourceManager.GetString("unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümleleri Göster.
        /// </summary>
        internal static string viewentries {
            get {
                return ResourceManager.GetString("viewentries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketleri Göster.
        /// </summary>
        internal static string viewtags {
            get {
                return ResourceManager.GetString("viewtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha önce bu cümleye oy verdiniz.
        /// </summary>
        internal static string votedbefore {
            get {
                return ResourceManager.GetString("votedbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cümleleri Oyla.
        /// </summary>
        internal static string votesentences {
            get {
                return ResourceManager.GetString("votesentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıda başkalarının yazdığı cümleler var. Oy ver, hikaye senin seçtiğin şekilde devam etsin..
        /// </summary>
        internal static string votinglabel {
            get {
                return ResourceManager.GetString("votinglabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OYLAMA AŞAMASI.
        /// </summary>
        internal static string votingphase1 {
            get {
                return ResourceManager.GetString("votingphase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şu anda cümle yazamıyorsun. Ama sağ taraftan diğer cümleleri oylayabilirsin..
        /// </summary>
        internal static string votingphase2 {
            get {
                return ResourceManager.GetString("votingphase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonraki adım bekleniyor....
        /// </summary>
        internal static string waitingfornextstep {
            get {
                return ResourceManager.GetString("waitingfornextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin’e hoş geldiniz!.
        /// </summary>
        internal static string welcome1 {
            get {
                return ResourceManager.GetString("welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÜMLEYİ YAZIN.
        /// </summary>
        internal static string welcome2 {
            get {
                return ResourceManager.GetString("welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonsuz Metin’de hikaye senin yazdığın cümleye göre devam edecek. .
        /// </summary>
        internal static string welcome3 {
            get {
                return ResourceManager.GetString("welcome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba,.
        /// </summary>
        internal static string welcome4 {
            get {
                return ResourceManager.GetString("welcome4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SONSUZ METİN’E HOŞ GELDİN.
        /// </summary>
        internal static string welcome5 {
            get {
                return ResourceManager.GetString("welcome5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook hesabınla giriş yap ve bu hiç bitmeyecek anlatıya katkıda bulun. .
        /// </summary>
        internal static string welcome6 {
            get {
                return ResourceManager.GetString("welcome6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile Giriş.
        /// </summary>
        internal static string welcome7 {
            get {
                return ResourceManager.GetString("welcome7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha önce bu kısım için zaten entry girmiştiniz.
        /// </summary>
        internal static string youpostedbefore {
            get {
                return ResourceManager.GetString("youpostedbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÜMLEN SEÇİLDİ.
        /// </summary>
        internal static string yourentrychosen {
            get {
                return ResourceManager.GetString("yourentrychosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÜMLEN GÖNDERİLDİ..
        /// </summary>
        internal static string yourentrysubmitted {
            get {
                return ResourceManager.GetString("yourentrysubmitted", resourceCulture);
            }
        }
    }
}
